name: build push and deploy
on:
   workflow_dispatch: # Allows manual triggering of the workflow
  #push:
    branches: 
      - main
   pull_request:
    branches:
      - main
   permissions: 
    id-token: write 
    contents: read
    # Required for the workflow to run
env:
  AWS_REGION: us-east-1
  AWS_ROLE: ${{ secrets.AWS_CREDENTIAL_ROLE }}
  ECR_REPO_NAME: dev
  IMAGE_TAG: ${{github.run_number}}
jobs:
    build:
      runs-on: ubuntu-latest # Use the latest Ubuntu runner ghithub runners provide
      steps:
        - name: Checkout code or clone repository
          uses: actions/checkout@v3

        - name: Aws credential setup
          uses: aws-actions/configure-aws-credentials@v4
            with:
               role-to-assume: ${{ env.AWS_ROLE }}   #OIDC of the role to assume
               aws-region: ${{ env.AWS_REGION }}
         
        - name: Loging to ecr
          uses: aws-actions/amazon-ecr-login@v1
          id: ecr-login
          

        - name: Build, tag, and push Docker image
          id: build-image
            run: |
                docker build -t ${{ steps.ecr-login.outputs.registry }}/${{ env.ECR_REPO_NAME }}:${{env.IMAGE_TAG}} .
                docker tag my-app:latest ${{ secrets.AWS_ECR_REGISTRY }}/my-app:latest
                docker push ${{ steps.ecr-login.outputs.registry }}/${{ env.ECR_REPO_NAME }}:${{env.IMAGE_TAG}}

        - name: Deploy to AWS S3
          uses: jakejarvis/s3-sync-action@master
          with:
            args: --acl public-read --follow-symlinks --delete
         